version: '3.9'

services:
  test_db:
    image: postgres:latest
    restart: always
    container_name: hackforms-hub-integration-test-prisma
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  live_db:
    image: postgres:latest
    restart: always
    container_name: hackforms-hub-integration-live-prisma
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    